### ISSUE TITLE
Crawler JSON format

### ISSUE THREAD

**Issue by shraiwi** [gt-scheduler/crawler#14]
Hi, I'm currently trying to use the .json files produced by this crawler for a personal project, but a lot of the data is unlabelled. What is the general structure of the file? I've tried to reverse-engineer it, but the exact values in the objects in the `courses` field elude me.

**Comment by jazeved0** [comment]
The main data files produced are admittedly quite unintuitive (lots of unlabeled tuples and integer references into "caches"). This was initially done a long time ago, so I don't know exactly why it was done that way, but my hunch is that it was to decrease the overall size of the JSON files that need to get loaded by the web app. Either way, the reverse-engineering was luckily already done for you in https://github.com/GTBitsOfGood/gt-scheduler/issues/1#issue-702207432, so you can just use the type file linked below.

For completeness, these are all of the files produced by the crawler (feel free to use them for whatever you want):

- main data files (i.e. https://gt-scheduler.github.io/crawler/202008.json): these correspond to the `TermData` type in https://github.com/gt-scheduler/crawler/blob/main/src/types.ts#L6. This syntax is TypeScript type syntax, which you can find documentation for [here](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) if you're unfamiliar with it.
- final schedule files (i.e. https://gt-scheduler.github.io/crawler/202302_Finals.csv): these are pretty intuitive; the base data is a direct parsing of [the PDF files released by the registrar](https://registrar.gatech.edu/files/202208%20Final%20Exam%20Matrix.pdf)
- index file (at https://gt-scheduler.github.io/crawler/index.json): this doesn't have its own TypeScript type in the code, but it has a simple structure of `{ terms: string[]; }` and is created [here](https://github.com/gt-scheduler/crawler/blob/main/src/steps/writeIndex.ts#L23).

Feel free to re-open the issue if you have further related questions/follow-ups.
